import path from 'path'
import webpack from 'webpack'
import HtmlWebpackPlugin from 'html-webpack-plugin'
// PostCSS plugins
import postcssFocus from 'postcss-focus'
import rucksack from 'rucksack-css'
import lost from 'lost'
import base from './config.base.babel'

module.exports = base({
    mode: 'development',
    devtool: 'cheap-module-source-map',
    output: {
        // Compile into js/build.js
        path: path.resolve(__dirname, '..', 'build'),
        filename: '[name].js',
        chunkFilename: '[name].chunk.js?',
        publicPath: '/',
    },
    // Add hot reloading in development
    entry: {
        main: [
            'babel-polyfill',
            'eventsource-polyfill', // necessary for hot reloading with IE
            'webpack-hot-middleware/client?reload=true',
            path.join(__dirname, '..', 'src/main.js'), // Start with js/app.js
        ],
    },
    // Load the CSS in a style tag in development
    cssLoaders: [{
        loader: 'style-loader',
    }, {
        loader: 'css-loader',
        options: {
            importLoaders: 1,
            sourceMap: true,
        },
    }],
    // Load Stylus with SourceMaps
    stylusLoaders: [{
        loader: 'style-loader',
    }, {
        loader: 'css-loader',
        options: {
            importLoaders: 1,
            sourceMap: true,
            localIdentName: '[local]___[hash:base64:10]',
        },
    }, {
        loader: 'stylus-loader',
    }],
    // Process the CSS with PostCSS
    stylusPlugins: [
        lost(),
        postcssFocus(), // Add a :focus to every :hover
        rucksack({
            autoprefixer: true,
            fallbacks: true,
        }),
    ],
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NamedModulesPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        }),
    ],
})
